"""add estimated_cost and job_card_ref to damage_logs

Revision ID: c14eb575cbf2
Revises: e9cb719ffd75
Create Date: 2026-07-25 04:26:21.685214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14eb575cbf2'
down_revision = 'e9cb719ffd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('damage_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('job_card_ref', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('damage_logs', schema=None) as batch_op:
        batch_op.drop_column('job_card_ref')
        batch_op.drop_column('estimated_cost')

    # ### end Alembic commands ###
